general_settings:
  master_key: sk-1234
  store_model_in_db: True
  database_connection_pool_limit: 10
  proxy_batch_write_at: 1

litellm_settings:
  drop_params: True
  num_retries: 5
  request_timeout: 600
  telemetry: False
